# This is a basic workflow to help you get started with Actions

name: Environment Setup

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Dependencies1
        run: |
            mydir="$PWD"
            export THORNADO_DIR=$mydir
            sudo apt-get update -y
            sudo apt-get install -y libhdf5-mpi-dev libhdf5-dev
            ## hdf5
            #git clone https://github.com/HDFGroup/hdf5.git
            #export HDF5_DIR=$mydir/hdf5/install
            #mkdir $HDF5_DIR
            #cd hdf5
            source Distributions/Workflow/SetEnvironment.sh ubuntu
            cd Distributions/UnitTests/Opacities/Executables
            pwd
            source Distributions/Workflow/SetEnvironment.sh ubuntu
            make wlReadOpacityTableTest
            make clobber
