name: setting up

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  # Basic jobs to checkout and compile code.

  build:
    runs-on: ubuntu-latest
    env: 
        WEAKLIB_MACHINE: ubuntu
        
    steps:
      - uses: actions/checkout@v2
        with: 
            ref: 'master'
      - run: |
           mydir="$PWD"
           export WEAKLIB_DIR=$mydir
           sudo apt-get update -y
           sudo apt-get install -y libhdf5-dev liblapack-dev libopenmpi-dev
           export HDF5_DIR=/usr/lib/x86_64-linux-gnu/hdf5/serial
           ls $HDF5_DIR
           pwd
           ls
           source Distributions/Workflow/SetEnvironment.sh ubuntu
           cd Distributions/UnitTests/Opacities/Executables
           env
           make clobber
           make
